### ISSUE TITLE
Adding cabal-install to the docker images 

### ISSUE THREAD

**Issue by liganega** [jamesdbrock/learn-you-a-haskell-notebook#14]
I'd like to add some haskell packages such as Data.Nat from the Hackage to the __YOUR__ docker images, _crosscompass/ihaskell-notebook_. When trying to install cabal-command using the following command

> sudo apt install cabal-command

a password for jovyan is asked. 

What is the password, or is there other ways to install haskell packages?

**Comment by jamesdbrock** [comment]
You can install more packages in the docker image using [`Haskell Stack`](https://docs.haskellstack.org/en/stable/README/).

You can even use the Haskell `stack` command from inside the Jupyter session: https://github.com/jamesdbrock/ihaskell-notebook#installing-haskell-packages
